# Generated by Django 3.1 on 2020-08-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('SecureGuard', 'SecureGuard'), ('GeneralUser', 'GeneralUser')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_user_first_name', models.CharField(max_length=100)),
                ('general_user_last_name', models.CharField(max_length=100)),
                ('general_user_type', models.CharField(max_length=100)),
                ('general_user_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('home_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('home_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('village_address', models.CharField(blank=True, max_length=200, null=True)),
                ('village_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('village_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('village_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_number', models.IntegerField(default=0)),
                ('zone_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('zone_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('zone_last_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.CreateModel(
            name='SecureGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_firstname', models.CharField(max_length=100)),
                ('secure_lastname', models.CharField(max_length=100)),
                ('secure_type', models.CharField(max_length=100)),
                ('secure_join_date', models.DateTimeField(blank=True, null=True)),
                ('secure_left_date', models.DateTimeField(blank=True, null=True)),
                ('secure_work_start_time', models.DateTimeField(blank=True, null=True)),
                ('secure_work_end_time', models.DateTimeField(blank=True, null=True)),
                ('secure_work_period', models.DateTimeField(blank=True, null=True)),
                ('secure_current_location', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('secure_current_location_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('secure_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company')),
                ('secure_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('secure_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
                ('secure_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_content', models.CharField(max_length=200)),
                ('qr_type', models.CharField(max_length=20)),
                ('qr_format', models.CharField(max_length=20)),
                ('qr_format_detail', models.CharField(max_length=100)),
                ('qr_car_number', models.CharField(max_length=200)),
                ('qr_car_color', models.CharField(max_length=100)),
                ('qr_car_brand', models.CharField(max_length=100)),
                ('qr_enter_time', models.DateTimeField(blank=True, null=True)),
                ('qr_inside_time', models.DateTimeField(blank=True, null=True)),
                ('qr_user_time', models.DateTimeField(blank=True, null=True)),
                ('qr_exit_time', models.DateTimeField(blank=True, null=True)),
                ('qr_enter_status', models.BooleanField(default=False)),
                ('qr_inside_status', models.BooleanField(default=False)),
                ('qr_user_status', models.BooleanField(default=False)),
                ('qr_exit_status', models.BooleanField(default=False)),
                ('qr_enter_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_enter_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_inside_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_inside_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_user_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_user_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_exit_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_exit_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('qr_complete_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_enter_secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_enter_secure', to='first_api.secureguard')),
                ('qr_exit_secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_exit_secure', to='first_api.secureguard')),
                ('qr_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home')),
                ('qr_inside_secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_inside_secure', to='first_api.secureguard')),
                ('qr_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.generaluser')),
                ('qr_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='home_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone'),
        ),
    ]
