# Generated by Django 3.1 on 2020-08-12 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_user_first_name', models.CharField(max_length=100)),
                ('general_user_last_name', models.CharField(max_length=100)),
                ('general_user_type', models.CharField(max_length=100)),
                ('general_user_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('home_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('home_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village'),
        ),
        migrations.CreateModel(
            name='SecureGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_firstname', models.CharField(max_length=100)),
                ('secure_lastname', models.CharField(max_length=100)),
                ('secure_type', models.CharField(max_length=100)),
                ('secure_join_date', models.DateTimeField(blank=True, null=True)),
                ('secure_left_date', models.DateTimeField(blank=True, null=True)),
                ('secure_work_start_time', models.DateTimeField(blank=True, null=True)),
                ('secure_work_end_time', models.DateTimeField(blank=True, null=True)),
                ('secure_work_period', models.DateTimeField(blank=True, null=True)),
                ('secure_current_location', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('secure_current_location_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('secure_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company')),
                ('secure_username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('secure_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
                ('secure_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_content', models.CharField(max_length=200)),
                ('qr_type', models.CharField(max_length=20)),
                ('qr_format', models.CharField(max_length=20)),
                ('qr_format_detail', models.CharField(max_length=100)),
                ('qr_car_number', models.CharField(max_length=200)),
                ('qr_car_color', models.CharField(max_length=100)),
                ('qr_car_brand', models.CharField(max_length=100)),
                ('qr_enter_time', models.DateTimeField(blank=True, null=True)),
                ('qr_inside_time', models.DateTimeField(blank=True, null=True)),
                ('qr_user_time', models.DateTimeField(blank=True, null=True)),
                ('qr_exit_time', models.DateTimeField(blank=True, null=True)),
                ('qr_enter_status', models.BooleanField(default=False)),
                ('qr_inside_status', models.BooleanField(default=False)),
                ('qr_user_status', models.BooleanField(default=False)),
                ('qr_exit_status', models.BooleanField(default=False)),
                ('qr_enter_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_enter_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_inside_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_inside_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_user_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_user_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_exit_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_exit_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=11)),
                ('qr_complete_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home')),
                ('qr_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.generaluser')),
                ('qr_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='home_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone'),
        ),
    ]
