# Generated by Django 3.1 on 2020-12-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointobservationrecord',
            unique_together=set(),
        ),
    ]
