# Generated by Django 3.1 on 2020-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0002_auto_20200828_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
