# Generated by Django 3.1 on 2020-08-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0002_home_home_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='general_user_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='general_user_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village'),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='general_user_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone'),
        ),
    ]
