# Generated by Django 3.1 on 2020-08-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0002_auto_20200812_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_enter_secure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_enter_secure', to='first_api.secureguard'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_exit_secure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_exit_secure', to='first_api.secureguard'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_inside_secure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qr_inside_secure', to='first_api.secureguard'),
        ),
    ]
