# Generated by Django 3.1 on 2021-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0002_auto_20201228_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
