# Generated by Django 3.1 on 2020-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0003_auto_20200828_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_car_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_home_number',
            field=models.CharField(max_length=100),
        ),
    ]
