# Generated by Django 3.1 on 2021-02-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0003_auto_20210106_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
