# Generated by Django 3.1 on 2020-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0003_auto_20200821_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_first_name',
            new_name='gen_user_firstname',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_home',
            new_name='gen_user_home',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_last_name',
            new_name='gen_user_lastname',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_type',
            new_name='gen_user_type',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_username',
            new_name='gen_user_username',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_village',
            new_name='gen_user_village',
        ),
        migrations.RenameField(
            model_name='generaluser',
            old_name='general_user_zone',
            new_name='gen_user_zone',
        ),
        migrations.AddField(
            model_name='generaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
