# Generated by Django 3.1 on 2020-08-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0004_auto_20200829_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_user_lat',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_user_lon',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_home_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_home_lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
