# Generated by Django 3.1 on 2020-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0004_auto_20200823_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='gen_user_type',
            field=models.CharField(choices=[('ลูกบ้าน', 'ลูกบ้าน'), ('กรรมการหมู่บ้าน', 'กรรมการหมู่บ้าน'), ('ผู้ดูแลหมู่บ้าน', 'ผู้ดูแลหมู่บ้าน')], max_length=100),
        ),
    ]
