# Generated by Django 3.1 on 2020-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0005_auto_20200823_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='gen_user_type',
            field=models.CharField(choices=[('Villager', 'Villager'), ('Manager', 'Manager'), ('Caretaker', 'Caretaker')], max_length=100),
        ),
    ]
