# Generated by Django 3.1 on 2020-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0006_auto_20200829_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_detail',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_livehome_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_car_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_car_color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_car_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_home_number',
            field=models.CharField(max_length=20),
        ),
    ]
