# Generated by Django 3.1 on 2020-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0008_auto_20200825_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True),
        ),
    ]
