# Generated by Django 3.1 on 2020-09-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0009_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_checkin_time', models.DateTimeField(blank=True, null=True)),
                ('inspect_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('inspect_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.checkpoint')),
            ],
        ),
    ]
