# Generated by Django 3.1 on 2020-08-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0010_auto_20200825_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=100)),
                ('point_active', models.BooleanField(default=True)),
                ('point_lat', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('point_lon', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('is_active', models.BooleanField(default=True)),
                ('point_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
                ('point_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone')),
            ],
        ),
    ]
