# Generated by Django 3.1 on 2020-09-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0010_pointinspection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointinspection',
            old_name='inspect_point',
            new_name='inspect_checkpoint',
        ),
        migrations.AddField(
            model_name='pointinspection',
            name='insepect_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.work'),
        ),
        migrations.AddField(
            model_name='pointinspection',
            name='inspect_secure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.secureguard'),
        ),
        migrations.AddField(
            model_name='pointinspection',
            name='inspect_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village'),
        ),
        migrations.AddField(
            model_name='pointinspection',
            name='inspect_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone'),
        ),
    ]
