# Generated by Django 3.1 on 2020-09-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0011_auto_20200901_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCheckingCheckPointList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='PointObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_hour_split', models.IntegerField(default=0)),
                ('observation_date', models.DateField(auto_now_add=True)),
                ('observation_secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.secureguard')),
                ('observation_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
                ('observation_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.work')),
                ('observation_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='PointObservationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_checkin_time', models.DateTimeField(blank=True, null=True)),
                ('observation_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('observation_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.checkpoint')),
                ('observation_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.pointobservation')),
            ],
        ),
        migrations.DeleteModel(
            name='PointInspection',
        ),
        migrations.AddField(
            model_name='pointcheckingcheckpointlist',
            name='observation_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.pointobservation'),
        ),
    ]
