# Generated by Django 3.1 on 2020-08-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0012_auto_20200826_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='point_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('SecureBoss', 'SecureBoss'), ('SecureGuard', 'SecureGuard'), ('GeneralUser', 'GeneralUser')], max_length=20),
        ),
    ]
