# Generated by Django 3.1 on 2020-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0013_auto_20200826_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureguard',
            name='secure_type',
            field=models.CharField(choices=[('SecureBoss', 'SecureBoss'), ('Enter', 'Enter'), ('Exit', 'Exit'), ('Inside', 'Inside')], max_length=100),
        ),
    ]
