# Generated by Django 3.1 on 2020-09-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0013_auto_20200902_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointObservationCheckPointList',
            new_name='PointObservationPointList',
        ),
    ]
