# Generated by Django 3.1 on 2020-09-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0014_auto_20200902_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointObservationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_checkin_time', models.DateTimeField(blank=True, null=True)),
                ('observation_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkpoint_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.checkpoint')),
                ('observation_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.pointobservation')),
            ],
        ),
        migrations.DeleteModel(
            name='PointObservationDetail',
        ),
    ]
