# Generated by Django 3.1 on 2020-08-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0016_work_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secureguard',
            name='secure_work_period',
        ),
        migrations.AddField(
            model_name='secureguard',
            name='secure_work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.work'),
        ),
    ]
