# Generated by Django 3.1 on 2020-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0016_auto_20200902_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointobservation',
            name='observation_date',
            field=models.CharField(max_length=10),
        ),
    ]
