# Generated by Django 3.1 on 2020-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0017_auto_20200827_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_format',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_format_detail',
        ),
        migrations.AddField(
            model_name='home',
            name='home_digit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_home_number',
            field=models.IntegerField(null=True),
        ),
    ]
