# Generated by Django 3.1 on 2020-09-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0017_auto_20200902_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointobservation',
            unique_together={('observation_village', 'observation_zone', 'observation_work', 'observation_secure', 'observation_date')},
        ),
        migrations.AlterUniqueTogether(
            name='pointobservationpointlist',
            unique_together={('observation_pk', 'checkpoint_pk')},
        ),
        migrations.AlterUniqueTogether(
            name='pointobservationrecord',
            unique_together={('observation_pk', 'observation_timeslot', 'checkpoint_pk')},
        ),
    ]
