# Generated by Django 3.1 on 2020-09-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0018_auto_20200902_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFeePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_period_name', models.CharField(max_length=100)),
                ('fee_start', models.DateTimeField(blank=True, null=True)),
                ('fee_end', models.DateTimeField(blank=True, null=True)),
                ('fee_deadline', models.DateTimeField(blank=True, null=True)),
                ('fee_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid_date', models.DateTimeField(blank=True, null=True)),
                ('fee_house_space', models.FloatField(default=0)),
                ('fee_amount', models.FloatField(default=0)),
                ('fee_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home')),
            ],
        ),
    ]
