# Generated by Django 3.1 on 2020-08-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0018_auto_20200828_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='home_digit',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.company'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.zone'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.IntegerField(null=True),
        ),
    ]
