# Generated by Django 3.1 on 2020-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0019_maintenancefee_maintenancefeeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancefee',
            name='fee_paid_status',
            field=models.BooleanField(default=True),
        ),
    ]
