# Generated by Django 3.1 on 2020-08-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0019_auto_20200828_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_home_number',
            field=models.IntegerField(default=0),
        ),
    ]
