# Generated by Django 3.1 on 2020-09-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0020_maintenancefee_fee_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancefee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenancefeeperiod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
