# Generated by Django 3.1 on 2020-09-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0022_auto_20200906_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancefee',
            name='fee_paid_date',
        ),
        migrations.RemoveField(
            model_name='maintenancefeeperiod',
            name='fee_deadline',
        ),
        migrations.RemoveField(
            model_name='maintenancefeeperiod',
            name='fee_end',
        ),
        migrations.RemoveField(
            model_name='maintenancefeeperiod',
            name='fee_start',
        ),
    ]
