# Generated by Django 3.1 on 2020-09-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0024_auto_20200906_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceFee',
            new_name='MaintenanceFeeRecord',
        ),
    ]
