# Generated by Django 3.1 on 2020-09-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0027_auto_20200908_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_thai_choice', models.CharField(max_length=100)),
                ('vote_eng_choice', models.CharField(max_length=100)),
                ('vote_chinese_choice', models.CharField(max_length=100)),
                ('vote_confirmed_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoteTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_thai_topic', models.CharField(max_length=100)),
                ('vote_eng_topic', models.CharField(max_length=100)),
                ('vote_chinese_topic', models.CharField(max_length=100)),
                ('vote_start_date', models.DateField(blank=True, null=True)),
                ('vote_end_date', models.DateField(blank=True, null=True)),
                ('vote_confirm_status', models.BooleanField(default=True)),
                ('vote_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_hiden', models.BooleanField(default=False)),
                ('vote_selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.votechoice')),
                ('vote_topic_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.votetopic')),
                ('vote_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village')),
            ],
        ),
        migrations.AddField(
            model_name='votechoice',
            name='vote_topic_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.votetopic'),
        ),
    ]
