# Generated by Django 3.1 on 2020-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0028_auto_20200908_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='votechoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votetopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
