# Generated by Django 3.1 on 2020-09-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0029_auto_20200908_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votechoice',
            old_name='vote_confirmed_status',
            new_name='vote_is_result',
        ),
    ]
