# Generated by Django 3.1 on 2020-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0030_auto_20200908_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votechoice',
            name='vote_chinese_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votechoice',
            name='vote_eng_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votechoice',
            name='vote_thai_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='vote_chinese_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='vote_eng_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='vote_thai_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
