# Generated by Django 3.1 on 2020-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0031_auto_20200908_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetopic',
            name='vote_thai_detail',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
