# Generated by Django 3.1 on 2020-09-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0032_votetopic_vote_thai_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord',
            name='vote_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='vote_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.generaluser'),
        ),
    ]
