# Generated by Django 3.1 on 2020-09-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0033_auto_20200909_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterecord',
            name='vote_village',
        ),
    ]
