# Generated by Django 3.1 on 2020-09-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0035_auto_20200909_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_date', models.DateTimeField(blank=True, null=True)),
                ('problem_type', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_detail', models.CharField(blank=True, max_length=400, null=True)),
                ('problem_feedback', models.CharField(blank=True, max_length=400, null=True)),
                ('problem_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.home')),
            ],
        ),
    ]
