# Generated by Django 3.1 on 2020-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0036_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
