# Generated by Django 3.1 on 2020-09-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0038_auto_20200910_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village'),
        ),
    ]
