# Generated by Django 3.1 on 2020-09-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0039_problem_problem_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secureguard',
            name='secure_current_location',
        ),
        migrations.RemoveField(
            model_name='secureguard',
            name='secure_current_location_time',
        ),
        migrations.AddField(
            model_name='secureguard',
            name='secure_now_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='secureguard',
            name='secure_now_location_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secureguard',
            name='secure_now_lontitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
