# Generated by Django 3.1 on 2020-09-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0040_auto_20200910_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_location_type', models.CharField(blank=True, max_length=30, null=True)),
                ('secure_location_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('secure_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('secure_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('secure_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.secureguard')),
            ],
        ),
    ]
