# Generated by Django 3.1 on 2020-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0041_securelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='gen_user_type',
            field=models.CharField(choices=[('ลูกบ้าน', 'ลูกบ้าน'), ('กรรมการหมู่บ้าน', 'กรรมการหมู่บ้าน'), ('ผู้ดูแลหมู่บ้าน', 'ผู้ดูแลหมู่บ้าน')], max_length=100),
        ),
        migrations.AlterField(
            model_name='secureguard',
            name='secure_type',
            field=models.CharField(choices=[('หัวหน้า', 'หัวหน้า'), ('ขาเข้า', 'ขาเข้า'), ('ขาออก', 'ขาออก'), ('ในหมู่บ้าน', 'ในหมู่บ้าน')], max_length=100),
        ),
    ]
