# Generated by Django 3.1 on 2020-09-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0042_auto_20200910_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureguard',
            name='secure_join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SecureWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.secureguard')),
                ('work_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.work')),
            ],
            options={
                'unique_together': {('secure_pk', 'work_pk')},
            },
        ),
    ]
