# Generated by Django 3.1 on 2020-09-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0043_auto_20200911_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='point_company',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='gen_user_company',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_company',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_company',
        ),
        migrations.RemoveField(
            model_name='secureguard',
            name='secure_company',
        ),
        migrations.RemoveField(
            model_name='village',
            name='village_company',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='zone_company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
