# Generated by Django 3.1 on 2020-09-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0048_remove_checkincheckpoint_point_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('working_in_out', models.CharField(blank=True, choices=[('เข้า', 'เข้า'), ('ออก', 'ออก')], max_length=5, null=True)),
                ('work_checkin_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.checkincheckpoint')),
                ('working_secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.secureguard')),
            ],
        ),
    ]
