# Generated by Django 3.1 on 2020-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0049_workingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingrecord',
            name='working_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
