# Generated by Django 3.1 on 2020-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0051_workingrecord_working_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='point_scan_distance',
            field=models.IntegerField(default=25),
        ),
    ]
