# Generated by Django 3.1 on 2020-09-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0052_setting_point_scan_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingrecord',
            name='working_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.work'),
        ),
    ]
