# Generated by Django 3.1 on 2020-09-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0055_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_enter_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
