# Generated by Django 3.1 on 2020-09-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0057_auto_20200916_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_exit_without_enter',
            field=models.BooleanField(default=False),
        ),
    ]
