# Generated by Django 3.1 on 2020-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0058_qrcode_qr_exit_without_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
