# Generated by Django 3.1 on 2020-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0059_auto_20200916_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('home_number', 'home_village')},
        ),
    ]
