# Generated by Django 3.1 on 2020-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0060_auto_20200916_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='house_space',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
