# Generated by Django 3.1 on 2020-09-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0062_home_home_vote_couta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home_vote_couta',
            new_name='home_vote_qouta',
        ),
    ]
