# Generated by Django 3.1 on 2020-09-21 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0065_auto_20200918_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureguard',
            name='secure_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
