# Generated by Django 3.1 on 2020-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0071_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manger_level',
            field=models.CharField(choices=[('VILLAGELEVEL', 'VILLAGELEVEL'), ('ZONELEVEL', 'ZONELEVEL')], max_length=100),
        ),
    ]
