# Generated by Django 3.1 on 2020-09-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0073_auto_20200924_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='is_active',
        ),
    ]
