# Generated by Django 3.1 on 2020-09-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0074_remove_manager_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manger_level',
            new_name='manager_level',
        ),
    ]
