# Generated by Django 3.1 on 2020-09-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0075_auto_20200924_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='first_api.village'),
        ),
    ]
