# Generated by Django 3.1 on 2020-10-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0077_votecount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votecount',
            unique_together={('vote_home', 'vote_topic_pk')},
        ),
    ]
